---
# tasks file for ronnywalter.reboot
- name: Reset UFW
  shell: ufw --force reset
  async: 300
  poll: 0

- name: Reboot box
  shell: sleep 2 && /sbin/shutdown -r now 'Rebooting box' 
  async: 300
  poll: 0

- name: Wait for system to become reachable again
  wait_for_connection:
      delay: 5
      timeout: 300