apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: net-debug
  labels:
    app: net-debug
spec:
  selector:
    matchLabels:
      app: net-debug
  template:
    metadata:
      labels:
        app: net-debug
    spec:
      containers:
        - name: netshoot
          image: nicolaka/netshoot:latest
          imagePullPolicy: Always
          command: ["sleep", "infinity"]
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"