renovate:
  cronjob:
    schedule: "0 5 * * *"
  renovate:
    config: |
      {
        "platform": "forgejo",
        "endpoint": "https://git.rwcloud.org/api/v1",
        "autodiscover": true,
        "autodiscoverFilter": ["ronny/*"],
        "onboarding": true,
        "requireConfig": "optional",
        "printConfig": false,
        "gitAuthor": "Renovate Bot <renovate@ronnywalter.de>"
      }
  existingSecret: renovate
  nodeSelector: 
    kubernetes.io/arch: amd64

  redis:
    # Configuration for a Redis subchart. Additional documentation at
    # https://github.com/bitnami/charts/tree/master/bitnami/redis

    # -- Enable the Redis subchart?
    enabled: false

    # -- Override the prefix of the redisHost
    nameOverride: ''

    # -- Disable replication by default
    architecture: standalone

    auth:
      # -- Don't require a password by default
      enabled: false

    # -- Override Kubernetes version for redis chart
    kubeVersion: ''