renovate:
  cronjob:
    schedule: "0 5 * * *"
  renovate:
    config: |
      {
        "platform": "forgejo",
        "endpoint": "https://git.rwcloud.org/api/v1",
        "autodiscover": true,
        "autodiscoverFilter": ["ronny/*"],
        "onboarding": true,
        "requireConfig": "required",
        "printConfig": false,
        "gitAuthor": "Renovate Bot <renovate@ronnywalter.de>",
        "platformAutomerge": true
      }
    # -- Options related to persistence
    persistence:
      cache:
        # -- Allow the cache to persist between runs
        enabled: true
        # -- Storage class of the cache PVC
        storageClass: "longhorn"
        # -- Storage size of the cache PVC
        storageSize: "5Gi"
  env:
    LOG_LEVEL: 'debug'

  existingSecret: renovate
  nodeSelector: 
    kubernetes.io/arch: amd64


