apiVersion: v1
kind: Service
metadata:
  name: {{ include "garage-ui.fullname" . }}
  labels:
    {{- include "garage-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3902
      protocol: TCP
      name: web
  selector:
    {{- include "garage-ui.selectorLabels" . | nindent 4 }}

