ansible_user: ronny
ansible_host: cloud-2.fritz.box
ansible_sudo_pass: "{{ lookup('env','TERRA_SUDO_PASS') }}"

rke2_type: agent

rke2_server_options:  
  - kubelet-arg:
    - node-ip=192.168.0.40,fd00:2222::7a55:36ff:fe02:abc4


# rke2_server_options:  
#   - "node-ip: 192.168.1.32"

k3s_agent:
  kubelet-arg:
  - "config=/etc/rancher/k3s/kubelet-config.yaml"