ansible_user: ronny
ansible_host: pi-2.local
ansible_sudo_pass: "{{ lookup('env','TERRA_SUDO_PASS') }}"

k3s_control_node: false

# k3s_agent:
#   node-taint: pi-node=true:NoSchedule
#   node-label: location=lan
  #node-ip: 100.70.19.73
  #flannel-iface: 'tailscale0'

tailscale_args: "--advertise-routes={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/32 --accept-routes --accept-dns=false"