---
image:
  repository: deconzcommunity/deconz
  tag: 2.29.2

env:
  VNC_MODE: "1"
  VNC_PORT: "5900"
  WEB_PORT: "80"
  WS_PORT: "443"
  VERBOSE: "1"
  TZ: "Europe/Berlin"

serviceAccountName: deconz

securityContext:
  privileged: true

vnc:
  create: false
  secretName: deconz-vnc
  password: changeme

## nodeSelector is used to select the node where the pod will be scheduled
## label the node that has the USB device.
## with the label "usb=zigbee" or change the value to match your node label
nodeSelector:
  feature.node.kubernetes.io/usb-02_1cf1_0030.present: true

pvc:
  name: deconz-config
  storageClassName: longhorn
  size: 2Gi


conbee:
  devicePath: /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2429022-if00

service:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: websocket
      port: 443
      targetPort: websocket
    - name: vnc
      port: 5900
      targetPort: vnc

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: deconz.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - deconz.example.com
      secretName: deconz-tls

