apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: k8up-schedule
spec:
  backup:
    podSecurityContext:
      runAsUser: 0
    schedule: '05 2 * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
  check:
    schedule: '30 3 * * *'
  prune:
    schedule: '30 3 * * *'
    retention:
      keepLast: 5
      keepDaily: 7