apiVersion: v1
kind: Service
metadata:
  name: diskstation-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  clusterIP: None
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: diskstation-service
  labels:
    kubernetes.io/service-name: diskstation-service
addressType: IPv4
ports:
- name: http
  port: 5000
endpoints:
- addresses:
  - 192.168.0.3
  conditions: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lan-service-diskstation
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  rules:
  - host: ds.ronnywalter.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: diskstation-service
            port:
              number: 5000
  tls:
  - hosts:
    - ds.ronnywalter.de
    secretName: ds-tls