###############################################################################
# Service (unverändert)
###############################################################################
apiVersion: v1
kind: Service
metadata:
  name: diskstation-service
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: 5000
---
###############################################################################
# EndpointSlice (unverändert)
###############################################################################
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: diskstation-service
  namespace: default
  labels:
    kubernetes.io/service-name: diskstation-service
addressType: IPv4
ports:
  - name: http
    port: 5000
    protocol: TCP
endpoints:
  - addresses:
      - 192.168.0.3
    conditions: {}
---
###############################################################################
# Certificate (cert-manager übernimmt TLS)
###############################################################################
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ds-cert
  namespace: default
spec:
  secretName: ds-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - ds.ronnywalter.de
---
###############################################################################
# Traefik IngressRoute
###############################################################################
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: diskstation
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ds.ronnywalter.de`)
      services:
        - name: diskstation-service
          port: 5000
          scheme: http
  tls:
    secretName: ds-tls