###############################################################################
# Service
###############################################################################
apiVersion: v1
kind: Service
metadata:
  name: diskstation-service
  namespace: default
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
###############################################################################
# Endpoints (statt EndpointSlice!)
###############################################################################
apiVersion: v1
kind: Endpoints
metadata:
  name: diskstation-service
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.0.3
    ports:
      - name: http
        port: 5000
---
###############################################################################
# Certificate
###############################################################################
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ds-cert
  namespace: default
spec:
  secretName: ds-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - ds.ronnywalter.de
---
###############################################################################
# IngressRoute
###############################################################################
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: diskstation
  namespace: default
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Rancher
    gethomepage.dev/group: System
    gethomepage.dev/icon: synology-dark.png
    gethomepage.dev/name: Diskstation
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ds.ronnywalter.de`)
      services:
        - name: diskstation-service
          port: 5000
          scheme: http
  tls:
    secretName: ds-tls