###############################################################################
# Service
###############################################################################
apiVersion: v1
kind: Service
metadata:
  name: haproxy-service
  namespace: default
spec:
  ports:
    - name: http
      port: 8404
      targetPort: 8404
---
###############################################################################
# Endpoints (statt EndpointSlice!)
###############################################################################
apiVersion: v1
kind: Endpoints
metadata:
  name: haproxy-service
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.0.225
    ports:
      - name: http
        port: 8404
---
###############################################################################
# Certificate
###############################################################################
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: haproxy-cert
  namespace: default
spec:
  secretName: haproxy-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - haproxy.rwcloud.org
---
###############################################################################
# Middlewares
###############################################################################
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-auth
  namespace: default
spec:
  forwardAuth:
    address: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - Authorization
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: geblock
  namespace: default
spec:
  plugin:
    geoblock:
      silentStartUp: false
      allowLocalRequests: true
      logLocalRequests: false
      logAllowedRequests: false
      logApiRequests: false
      api: "https://get.geojs.io/v1/ip/country/{ip}"
      apiTimeoutMs: 500
      cacheSize: 25
      forceMonthlyUpdate: true
      allowUnknownCountries: false
      unknownCountryApiResponse: "nil"
      countries:
        - DE
      excludedPathPatterns:
        - "^[^/]+/health$"
        - "^[^/]+/status$"
---
###############################################################################
# IngressRoute
###############################################################################
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: haproxy
  namespace: default
  annotations:
    gethomepage.dev/href: "https://haproxy.rwcloud.org/stats"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: HAProxy
    gethomepage.dev/group: System
    gethomepage.dev/icon: haproxy.png
    gethomepage.dev/pod-selector: ""
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`haproxy.rwcloud.org`) && PathPrefix(`/stats`)
      middlewares:
        - name: oauth2-auth
        - name: geblock
      services:
        - name: haproxy-service
          port: 8404
          scheme: http
  tls:
    secretName: haproxy-tls