###############################################################################
# Service
###############################################################################
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: default
spec:
  ports:
    - name: http
      port: 9091
      protocol: TCP
      targetPort: 9091
---
###############################################################################
# Endpoints (externes LAN-Ziel)
###############################################################################
apiVersion: v1
kind: Endpoints
metadata:
  name: keycloak-service
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.0.3
    ports:
      - name: http
        port: 9091
        protocol: TCP
---
###############################################################################
# Certificate (cert-manager)
###############################################################################
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-cert
  namespace: default
spec:
  secretName: auth-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - auth.rwcloud.org
---
###############################################################################
# Traefik IngressRoute
###############################################################################
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`auth.rwcloud.org`)
      services:
        - name: keycloak-service
          port: 9091
          scheme: http
  tls:
    secretName: auth-tls