apiVersion: v2
name: kps
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 79.7.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: alertmanager-discord
    version: 1.3.2
    repository: https://k8s-at-home.com/charts/
  - name: prometheus-pushgateway
    version: 3.4.2
    repository: https://prometheus-community.github.io/helm-charts
